graphite:
  -
    period: 60
    timeunit: 'SECONDS'
    prefix: "CassandraSummitI2.${host.name}"
    hosts:
     - host: '10.10.10.XX'
       port: 2003
    predicate:
      color: "white"
      useQualifiedName: true
      patterns:
        - "^org.apache.cassandra.metrics.ClientRequest.+" # includes ClientRequestMetrics
        - "^org.apache.cassandra.metrics.CommitLog.+"
        - "^org.apache.cassandra.metrics.Client.+"
        - "^org.apache.cassandra.metrics.Compaction.+"
        - "^org.apache.cassandra.metrics.DroppedMessage.+"
        - "^org.apache.cassandra.metrics.ThreadPools.+"
        - "^org.apache.cassandra.metrics.ColumnFamily.summit_stress.+"
